# Generated by Django 6.0 on 2026-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the booking', null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the provider profile', null=True),
        ),
    ]
